# Generated by Django 6.0.6 on 2026-07-08 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('anomalies_found', models.IntegerField(default=0)),
                ('rows_pending_review', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('amount_inr', models.DecimalField(decimal_places=2, help_text='Amount converted to INR at a documented fixed rate (see DECISIONS.md)', max_digits=12)),
                ('date', models.DateField()),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('unequal', 'Unequal (explicit amounts)'), ('percentage', 'Percentage'), ('share', 'Share-based (ratios)')], default='equal', max_length=20)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending_review', 'Pending Review'), ('rejected', 'Rejected')], default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('source_row', models.IntegerField(blank=True, help_text='Original CSV row number, for traceability', null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='ledger.group')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='ledger.importbatch')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_paid', to='ledger.person')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='ledger.group')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='ledger.importbatch')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_paid', to='ledger.person')),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_received', to='ledger.person')),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('anomaly_type', models.CharField(choices=[('duplicate', 'Duplicate entry'), ('missing_field', 'Missing required field'), ('invalid_date', 'Invalid or wrong date'), ('ambiguous_date', 'Ambiguous date format'), ('name_variant', 'Name casing/typo/alias'), ('precision', 'Excess decimal precision'), ('split_math_invalid', 'Split percentages/shares do not resolve correctly'), ('misclassified', 'Settlement logged as expense (or vice versa)'), ('stale_membership', 'Includes a person outside their membership window'), ('non_member', 'Includes a person not in the group at all'), ('currency_mixed', 'Non-INR currency needing conversion'), ('negative_amount', 'Negative amount (possible refund)'), ('zero_amount', 'Zero-value row'), ('metadata_contradiction', 'split_type contradicts split_details'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('policy_applied', models.TextField(help_text='Which documented policy handled this, and what it did')),
                ('resolution_status', models.CharField(choices=[('auto_resolved', 'Auto-resolved by policy'), ('pending_review', 'Pending human approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('linked_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.expense')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='ledger.importbatch')),
                ('linked_settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField()),
                ('left_at', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ledger.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ledger.person')),
            ],
            options={
                'unique_together': {('group', 'person', 'joined_at')},
            },
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='ledger.expense')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='ledger.person')),
            ],
            options={
                'unique_together': {('expense', 'person')},
            },
        ),
    ]
